const media = [
  {
    title: 'Inclusive Design is for everyone',
    youtubeId: 'ISjbFDcGqhA',
    alt: 'Inclusive Design sketchnote',
    tag: 'ms01',
  },
  {
    title: 'Azure Functions de A à Z',
    youtubeId: 'MBC0_qOhkxc',
    alt: 'Azure Functions sketchnote',
    tag: 'ms02',
  },
  {
    title: 'Découvrez NestJS, le framework Node.js qui monte !',
    youtubeId: 'J2JSTsDVeOk',
    alt: 'NestJS sketchnote',
    tag: 'ms03',
  },
  {
    title: 'Project Fugu 🐡: A Better, Smoother and Sexier web',
    youtubeId: 'Hy3Gfgqyg18',
    alt: 'Project Fugu sketchnote',
    tag: 'ms04',
  },
  {
    title: 'Un environnement de dev propre et qui marche à tous les coups',
    youtubeId: 'djrbNMlXpug',
    alt: 'Dev Env sketchnote',
    tag: 'ms05',
  },
  {
    title: 'Tensorflow, there is no spoon',
    youtubeId: 'RC8ljOCSTJ4',
    alt: 'Tensorflow sketchnote',
    tag: 'ms06',
  },
  {
    title: 'Devenez un héros des GitHub Actions',
    youtubeId: 'fh2527R7mw8',
    alt: 'GitHub Actions sketchnote',
    tag: 'ms07',
  },
  {
    title: 'Microsoft Graph API & Toolkit',
    youtubeId: 'MNa_73qmUkA',
    alt: 'Graph API & Toolkit sketchnote',
    tag: 'ms08',
  },
  {
    title: 'Core dans le doute reboot appliqué à .Net',
    youtubeId: 's5LS2cvUIvY',
    alt: '.Net Core sketchnote',
    tag: 'ms09',
  },
  {
    title: 'Pimp my VSCode',
    youtubeId: 'mueaEPOs6iE',
    alt: 'Pimp my VSCode sketchnote',
    tag: 'ms10',
  },
  {
    title: 'The state of Angular Tooling',
    youtubeId: 'rEpf6LcEZZo',
    alt: 'Angular Tooling sketchnote',
    tag: 'ms11',
  },
  {
    title: 'Devops at Microsoft',
    youtubeId: 'RYbpVThlAHQ',
    alt: 'Devops at MS sketchnote',
    tag: 'ms12',
  },
  {
    title: 'Build an ML model with zero lines of code',
    youtubeId: 'ca7v1G-H6o4',
    alt: 'Build an ML model sketchnote',
    tag: 'ms13',
  },
  {
    title: 'Les Progressives Web Apps, au delà du buzzword',
    youtubeId: 'dRnQu8uSLnk',
    alt: 'PWA sketchnote',
    tag: 'ms14',
  },
];
// eslint-disable-next-line import/prefer-default-export
export const microsoftData = {
  fr: {
    title: 'Travail graphique pour Microsoft',
    description: 'Réalisation de 14 sketchnotes des conférences de MS Dev RoadShow.',
    highlightDescription: '14 sketchnotes',
    description2: 'En plus, l\'illustration de la couverture du livre duquel ces sketchnotes feront partie.',
    highlightDescription2: 'l\'illustration de la couverture',
    whatIs: 'Qu\'est-ce MS Dev Road Show?',
    mediaIllustration: 'La répresentation de chaque conférence technique',
    mediaVideo: 'Suivie de la vidéo de la conférence',
    media,
  },
  en: {
    title: 'Graphic work for Microsoft',
    description: 'Realization of 14 sketchnotes of MS Dev RoadShow conferences.',
    highlightDescription: '14 sketchnotes',
    description2: 'Also the cover illustration of the book, to which these sketchnotes will belong.',
    highlightDescription2: 'cover illustration',
    whatIs: 'What is MS Dev Road Show?',
    mediaIllustration: 'A visual representation of each technical talk',
    mediaVideo: 'Followed by the conference\'s video',
    media,
  },
  es: {
    title: 'Trabajo gráfico para Microsoft',
    description: 'Realización de 14 sketchnotes de las diferentes conferencias de MS Dev RoadShow.',
    highlightDescription: '14 sketchnotes',
    description2: 'Además, la ilustración de la portada del libro que reunirá estos sketchnotes.',
    highlightDescription2: 'ilustración de la portada',
    whatIs: '¿Qué es MS Dev Road Show?',
    mediaIllustration: 'Representación visual de cada conferencia técnica',
    mediaVideo: 'Seguida del video original',
    media,
  },
  eu: {
    title: 'Microsoft-entzat lan grafikoa',
    description: 'MS Dev RoadShow-ko konferentzia ezberdinen 14 sketchnote-ren burutzea.',
    highlightDescription: '14 sketchnote',
    description2: 'Gainera, sketchnote hauek bilduko dituen liburuaren azaleko marrazkia.',
    highlightDescription2: 'liburuaren azaleko marrazkia',
    whatIs: 'Zer da MS Dev Road Show?',
    mediaIllustration: 'Aurkezpen tekniko bakoitzaren adierazpen bisuala',
    mediaVideo: 'Aurkezpenaren bideoaz jarraitua',
    media,
  },
};
